export const foodItems = [
  {
    id: 1,
    image: "/images/food/burger.jpg",
    title: "Burger",
    category: "Hamburger",
    rating: 4.5,
    price: 10,
  },
  {
    id: 2,
    image: "/images/food/meat.jpg",
    title: "Meat",
    category: "Meat",
    rating: 4.5,
    price: 15,
  },
  {
    id: 3,
    image: "/images/food/noodles.jpg",
    title: "Noodles",
    category: "Noodles",
    rating: 4.5,
    price: 12,
  },
  {
    id: 4,
    image: "/images/food/salad.jpg",
    title: "Salad",
    category: "Salad",
    rating: 4.5,
    price: 8,
  },
  {
    id: 5,
    image: "/images/food/pizza.jpg",
    title: "Pizza",
    category: "pizza",
    rating: 4.5,
    price: 8,
  },
  {
    id: 6,
    image: "/images/food/mexican.jpg",
    title: "Mexican",
    category: "mexican",
    rating: 4.5,
    price: 8,
  },
  {
    id: 7,
    image: "/images/food/fish.jpg",
    title: "Fish",
    category: "fish",
    rating: 4.5,
    price: 8,
  },
  {
    id: 8,
    image: "/images/food/chicken.jpg",
    title: "Chicken",
    category: "chicken",
    rating: 4.5,
    price: 8,
  },
];
